config/routes.rb
BookingApp::Application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get "/users/:id/add_email", to: "users#add_email", via: [:get, :patch, :post], as: :add_user_email
  get "/contact", to: "contact#index"
  post "/contact", to: "contact#send_contact"
  get "/contact_us_result", to: "contact#contact_us_result"
  get "/merchant_page", to: "home#merchant_page", as: :merchant_page

  post "promotions/:blackout_id/cancel_blackout", to: "promotions#cancel_blackout", as: :cancel_blackout
  get "/merchants/:merchant_id/business", to: "employees#business", as: :employees_business

  devise_for :users, path: :auth,
    controllers: {
      omniauth_callbacks: :omniauth_callbacks,
      registrations: :registrations,
      confirmations: :confirmations
    }

  devise_scope :user do
    get "/auth/change_password", to: "registrations#edit_password"
    post "/auth/new_profile", to: "registrations#new_profile"
    get "/auth/check_user_unique", to: "registrations#check_user_unique"
    get "/auth/confirmation_success", to: "registrations#comfirmation_success"
    get "/auth/billing_card", to: "registrations#billing_card"
    post "/auth/billing_card", to: "registrations#create_billing_card"
    get "/auth/index_regis", to: "registrations#index_regis"
    get "/auth/check_email_regis", to: "registrations#check_email_regis"
    get "/auth/account_regis", to: "registrations#account_regis"
    post "/auth/get_info_account", to: "registrations#get_info_account"
    get "/auth/:id/card", to: "registrations#card", as: :auth_card
    put "/auth/:id/card", to: "registrations#update_card"
    get "/auth/check_email_present", to: "sessions#check_email_present"
    get "/auth/index", to: "sessions#index"
    get "/auth/destroy", to: "sessions#destroy"
    post "/auth/create", to: "passwords#create", as: :reset_password
    post "/auth/create_billing_card_merchant", to: "registrations#create_billing_card_merchant"
    get "/auth/redirect", to: "sessions#redirect"

  end

  root 'home#index'

  resources :home, except: [:index] do
    collection do
      get 'check_password_page'
      get 'check_pass'
      get :privacy_policy
    end
  end
  # get '*path' => 'home#index'

  resources :users do
    collection do
      post "new_step2"
      post "crop_avatar"
    end
    member do
      get "delete_account"
      post "send_reset_password"
      get "business_address"
    end
  end
  resources :faqs do
    collection do
      get "search"
    end
  end

  resources :bookings do
    collection do
      post "create_new_booking"
      post "payment_booking_merchant"
      post "payment_booking_client"
    end
  end
  resources :images do
    collection do
      post "upload_image"
      post "upload_image_step3"
      post "upload_image_from_angular"
    end
  end

  resources :promotions do
    member do
      get "share"
      get "check_deletion"
      get "customer_contacts"
      post "set_cancel_reactive_status"
      get "reset_pricing"
      patch "update_pricing"
      post "apply_blackout"
      put :publish_promotion
    end
    collection do
      get "get_cus_email"
      get "add_image"
      post "upload_image"
      get "show_inactive"
      post "get_current_rank"
      get "get_blackout_details"
    end
  end

  resources :temp_promotions

  resources :calendars,only:[:index] do
    collection do
      get "get_promotion_for_blackout"
      get "get_events"
      get "get_segmented_events"
      get "export_to_google_calendar"
    end
  end
  resources :categories, except: [:show, :new] do
    member do
      get "delete"
    end
    collection do
      get "check_categories_unique"
    end
  end

  resources :activities do
    member do
      get "view_day"
      get "cus_month_calendars"
      get "data_day"
      get "booked"
      resources :reviews
      post "bookmark"
      get "remove_bookmark"
      get "remove_past_life"
    end
    collection do
      post "book"
      get "genre"
      get "my_activity"
      get "load_image"
    end
  end
  resources :my_activities,only: [:destroy, :index] do
    member do
      get "contact", to: "my_activities#contact"
      post "contact", to: "my_activities#send_contact"
      get "destroy"
    end
    collection do
      post "cancel_booking"
    end
  end
  resources :history_v_moneys,only: [:index] do
  end
  # always the last routes
  match '*unmatched_route', :to => 'application#raise_not_found!', :via => :all
end

app/controllers/my_activities_controller.rb
class MyActivitiesController < ApplicationController
  ##
  # GET
  def index
    authorize! :book, Booking
    if params[:promotion_name].present?
      promotions = Promotion.where("LOWER(name) like ?", "%#{params[:promotion_name].downcase}%")
      if !current_user.admin
      @booked = current_user.bookings.where(status: true, promotion_id: promotions.ids).order("id DESC").page(params[:page])
      else
        @booked = Booking.where(status: true, promotion_id: promotions.ids).order("id DESC").page(params[:page])
      end
    else
      if !current_user.admin
      @booked = current_user.bookings.where("status=TRUE").order("id DESC").page(params[:page])
      else
        @booked = Booking.where("status=TRUE").order("id DESC").page(params[:page])
      end
    end
  end
  # GET /promotions/contact
  def contact
    authorize! :contact, User
    @detail = Promotion.select("user_id").find_by_id(params[:id]).user.merchant_detail
  end
  ##
  # POST /my_activities/contact
  def send_contact
    data = {}
    data[:email] = params[:contact][:email]
    data[:message] = params[:contact][:message]

    respond_to do |format|
      if UserMailer.delay.send_merchant_contact(data)
        format.js
      else
        format.html {render "contact"}
      end
    end
  end
  ##
  #GET
  def destroy
    @booked = Booking.find_by_id(params[:id])
    promotion = Promotion.select("user_id,price,discount_percent,discount_price,cancellation_fee").find_by_id(@booked.promotion_id)
    @deposit = promotion.discount_price - promotion.cancellation_fee
    @bussiness_name = promotion.user.merchant_detail.business_name
  end
  def cancel_booking
    if current_user.admin
      #refund real money
      billing = BillingDetail.where("user_id = ? AND always_use = TRUE", params_history[:user_id]).last
      deposit = update_create_v_money
      booked = Booking.find_by_id(params_history[:booking_id])
      begin
        ch = Stripe::Charge.retrieve(booked.charge_id)
        refund = ch.refunds.create(:amount => (deposit*100).to_i)
        HistoryVMoney.create(params_history.merge(amount: deposit))
      rescue Stripe::CardError => e
        flash[:alert] = e.message
        redirect_to :back
      end
      flash[:notice] = t("my_activities.cancel_promotion_confirm.deposit_msg", deposit: deposit)
      redirect_to my_activities_path
    else
      deposit = update_create_v_money
      user = User.find_by_id(params_history[:user_id])
      vitrual_money = user.virtual_money + deposit
      user.update(virtual_money: vitrual_money)
      HistoryVMoney.create(params_history.merge(amount: deposit))
      flash[:notice] = t("my_activities.cancel_promotion_confirm.deposit_msg", deposit: deposit)
      redirect_to my_activities_path
    end
  end
  def update_create_v_money
      booked = Booking.find_by_id(params_history[:booking_id])
      booked.status = false
      booked.save
      promotion = Promotion.select("user_id,price,discount_percent,discount_price,cancellation_fee").find_by_id(booked.promotion_id)
      deposit = promotion.discount_price - promotion.cancellation_fee
      return deposit
  end
  def params_history
    if current_user.admin
      params[:history_v_money][:action] = 1
    else
      params[:history_v_money][:action] = 0
    end
    params.require(:history_v_money).permit(:user_id, :promotion_id, :booking_id, :action)
  end
end

app/views/my_activities/_booked.html.haml
- if booked.size> 0
  - booked.each do |b|
    - promotion = b.promotion
    - if promotion != nil
      = render 'promotion_booked', :promotion => promotion, book: b
- else
  %tr
    %td= t("users.user.no_record")

app/views/my_activities/_cancel_promotion_confirm.html.haml
#cancel_promotion_confirm.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
        %h4#myModalLabel.modal-title= t(".confirmation")
      .modal-body
        .text-center
          %h4= t(".modal_msg_confirm", deposit: number_to_currency(deposit)).html_safe
          %h4= t(".check_term", name: bussiness_name)
        = form_for(HistoryVMoney.new, url: cancel_booking_my_activities_path, method: :post) do |f|
          =f.hidden_field :user_id, value: booked.user_id
          =f.hidden_field :booking_id, value: booked.id
          =f.hidden_field :promotion_id, value:  booked.promotion_id
          #btn_control.text-center
            .row
              .col-md-5.col-md-offset-1
                %button.btn.btn-default.btn-full{id: "booking_on_view_day", :type => "submit","data-id" => booked.id }= t(".yes_c_t_bk")
              .col-md-5
                %button.btn.btn-default.btn-full{id: "no_cancel",:type => "button", "aria-hidden" => "true", "data-dismiss" => "modal"}= t(".no_s")

app/views/my_activities/_contact_merchant_confirmation.html.haml
.center-block.align-center
  %p=t (".header")
  %p=t (".body")
  %p
    = link_to :ok, root_url, class: "btn btn-default"

app/views/my_activities/_promotion_booked.html.haml
%tr
  %td.col-a.text-center.col-md-4
    - if promotion.images.find_by_image_default(true).blank?
      = link_to  activity_path(promotion.id) do
        = image_tag("default_image.png", alt: "No Images", class: ".img-responsive img-thumbnail", id: "image_promotion_large_default", width: "100", height: "100")
    -else
      = link_to  activity_path(promotion.id) do
        = image_tag(promotion.images.find_by_image_default(true).image.url(:thumb), class: ".img-responsive img-thumbnail h_w_100", width: "100", height: "100")
  %td.col-b.col-md-8
    .row.content
      %table.no-border
        %tr
          %td
            %h4
              = link_to  activity_path(promotion.id), class: "list_promotion_a" do
                =promotion.name
      .row.no-padding
        .col-md-12.desciption.white_space
          =promotion.description
      .row.no-padding
        .col-md-12.desciption.white_space
          - time = Segment.find_by_id(book.segment_id).start_time.strftime("%I:%M %p")
          = t(".booked_msg", date: book.book_date.strftime("%B %d") , time: time)
      .clear-both
      .row.no-padding
        #share_health
          = link_to t(".share_health"), share_promotion_path(book.promotion_id), class: "btn btn-default"
  %td.col-c.text-right.col-md-4
    .content.col-md-12
      .row
        .col-md-5
          %h4
            = link_to t(".cancel"), my_activity_path(book.id), class: "btn btn-default btn-xs", remote: true
        .col-md-7
          %h4
            = link_to t(".contact_merchant"), contact_my_activity_path(book.promotion_id), class: "btn btn-default btn-xs"

app/views/my_activities/contact.html.haml
.col-md-8.col-md-offset-2
  #contact-page.well.form-border.form-custom
    %h4=t(".header", name: @detail.business_name)
    %form{ method: :post, role: :form, id: "contact-form", "data-remote" => "true"}
      = hidden_field_tag :authenticity_token, form_authenticity_token
      .form-group
        %label=t(".email_label")
        .row
          .col-md-4
            %input.form-control{ type: :email, name: "contact[email]", placeholder: t(".email_placeholder") }
      .form-group
        %label=t(".message_label")
        %textarea.form-control{ name: "contact[message]", placeholder: t(".message_placeholder"), rows: 5 }
      .row.text-right
        .col-md-12
          %input.btn.btn-primary{ type: "submit", value: t(".submit_button_value")}

app/views/my_activities/destroy.js.erb
$('#destroy_modal').html('<%= j render "my_activities/cancel_promotion_confirm", :booked => @booked, :deposit => @deposit, :bussiness_name => @bussiness_name %>');
$('#cancel_promotion_confirm').modal('show');

app/views/my_activities/index.html.haml
.col-md-10.col-md-offset-1
  #promotion_booking.well.form-border.form-custom
    .row#search_box_m_activities
      .col-md-8.col-sm-8.col-xs-10.col-md-offset-2.col-sm-offset-2.col-xs-offset-1.text-center
        = form_tag({:action => 'index'}, {:method => 'get', :role => "form", :id => 'search_form', :class => "form form-inline form-horizontal", :remote=> true}) do
          .row.text-center
            .form-group
              .control-label
                %label{:for => "promotion_name"}=t(".search_box")
                %input.form-control{ type: :input, name: "promotion_name", id: "promotion_name"}
                %input.btn.btn-default{ :id => "search_submit_activities", type: "submit",  :name => nil, value: t(".search"), :remote => true}
    .table-responsive
      %table.table-my-activities
        = render "my_activities/booked", booked: @booked
    .row.text-center#paganite_booked
      = paginate @booked, :remote => true
  #destroy_modal

app/views/my_activities/index.js.erb
$('.table-my-activities').html('<%= j render "my_activities/booked", booked: @booked %>');
$('#paganite_booked').html('<%= j (paginate(@booked, :remote => true).to_s) %>');

app/views/my_activities/send_contact.js.erb
$("#contact-page").html("<%= j render partial: 'my_activities/contact_merchant_confirmation' %>");