config/routes.rb
BookingApp::Application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get "/users/:id/add_email", to: "users#add_email", via: [:get, :patch, :post], as: :add_user_email
  get "/contact", to: "contact#index"
  post "/contact", to: "contact#send_contact"
  get "/contact_us_result", to: "contact#contact_us_result"
  get "/merchant_page", to: "home#merchant_page", as: :merchant_page

  post "promotions/:blackout_id/cancel_blackout", to: "promotions#cancel_blackout", as: :cancel_blackout
  get "/merchants/:merchant_id/business", to: "employees#business", as: :employees_business

  devise_for :users, path: :auth,
    controllers: {
      omniauth_callbacks: :omniauth_callbacks,
      registrations: :registrations,
      confirmations: :confirmations
    }

  devise_scope :user do
    get "/auth/change_password", to: "registrations#edit_password"
    post "/auth/new_profile", to: "registrations#new_profile"
    get "/auth/check_user_unique", to: "registrations#check_user_unique"
    get "/auth/confirmation_success", to: "registrations#comfirmation_success"
    get "/auth/billing_card", to: "registrations#billing_card"
    post "/auth/billing_card", to: "registrations#create_billing_card"
    get "/auth/index_regis", to: "registrations#index_regis"
    get "/auth/check_email_regis", to: "registrations#check_email_regis"
    get "/auth/account_regis", to: "registrations#account_regis"
    post "/auth/get_info_account", to: "registrations#get_info_account"
    get "/auth/:id/card", to: "registrations#card", as: :auth_card
    put "/auth/:id/card", to: "registrations#update_card"
    get "/auth/check_email_present", to: "sessions#check_email_present"
    get "/auth/index", to: "sessions#index"
    get "/auth/destroy", to: "sessions#destroy"
    post "/auth/create", to: "passwords#create", as: :reset_password
    post "/auth/create_billing_card_merchant", to: "registrations#create_billing_card_merchant"
    get "/auth/redirect", to: "sessions#redirect"

  end

  root 'home#index'

  resources :home, except: [:index] do
    collection do
      get 'check_password_page'
      get 'check_pass'
      get :privacy_policy
    end
  end
  # get '*path' => 'home#index'

  resources :users do
    collection do
      post "new_step2"
      post "crop_avatar"
    end
    member do
      get "delete_account"
      post "send_reset_password"
      get "business_address"
    end
  end
  resources :faqs do
    collection do
      get "search"
    end
  end

  resources :bookings do
    collection do
      post "create_new_booking"
      post "payment_booking_merchant"
      post "payment_booking_client"
    end
  end
  resources :images do
    collection do
      post "upload_image"
      post "upload_image_step3"
      post "upload_image_from_angular"
    end
  end

  resources :promotions do
    member do
      get "share"
      get "check_deletion"
      get "customer_contacts"
      post "set_cancel_reactive_status"
      get "reset_pricing"
      patch "update_pricing"
      post "apply_blackout"
      put :publish_promotion
    end
    collection do
      get "get_cus_email"
      get "add_image"
      post "upload_image"
      get "show_inactive"
      post "get_current_rank"
      get "get_blackout_details"
    end
  end

  resources :temp_promotions

  resources :calendars,only:[:index] do
    collection do
      get "get_promotion_for_blackout"
      get "get_events"
      get "get_segmented_events"
      get "export_to_google_calendar"
    end
  end
  resources :categories, except: [:show, :new] do
    member do
      get "delete"
    end
    collection do
      get "check_categories_unique"
    end
  end

  resources :activities do
    member do
      get "view_day"
      get "cus_month_calendars"
      get "data_day"
      get "booked"
      resources :reviews
      post "bookmark"
      get "remove_bookmark"
      get "remove_past_life"
    end
    collection do
      post "book"
      get "genre"
      get "my_activity"
      get "load_image"
    end
  end
  resources :my_activities,only: [:destroy, :index] do
    member do
      get "contact", to: "my_activities#contact"
      post "contact", to: "my_activities#send_contact"
      get "destroy"
    end
    collection do
      post "cancel_booking"
    end
  end
  resources :history_v_moneys,only: [:index] do
  end
  # always the last routes
  match '*unmatched_route', :to => 'application#raise_not_found!', :via => :all
end

app/models/user.rb
class User < ActiveRecord::Base

  ratyrate_rater
   
  TEMP_EMAIL_REGEX = /change@me.com/
  USER_TYPE = {
    merchant: "merchant",
    client: "client",
    admin: "admin"
  }

  attr_accessor :agree_with_tos, :type_sign_up, :search_email

  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :async
  ##
  # Relationships
  has_one :merchant_detail, dependent: :destroy
  has_one :billing_detail, dependent: :destroy
  # belongs_to :billing_detail, dependent: :destroy
  has_many :identitys, dependent: :destroy
  has_many :promotions, dependent: :destroy
  has_many :temp_promotions, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :categories
  has_many :history_v_moneys
  has_many :images
  has_many :reviews
  has_many :bookmarks
  
  ##
  # Nested models
  accepts_nested_attributes_for :merchant_detail, :billing_detail

  ##
  # Validates
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, uniqueness: true, on: :create
  validates :agree_with_tos, acceptance: true
  validates :email, presence: true
  delegate :can?, :cannot?, to: :ability

  def ability
    @ability ||= Ability.new(self)
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)
    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth.provider, auth.uid)
    user = identity.user ? identity.user : signed_in_resource
    user
  end

  ##
  # Check if user is admin
  def admin?
    self.admin
  end

  ##
  # Check if user is merchant
  def merchant?
    !self.admin? && self.user_type == USER_TYPE[:merchant]
  end

  ##
  # Check if user is client
  def client?
    self.user_type == USER_TYPE[:client]
  end

  def business_account?
    !Merchant.find(id).account_types.map(&:merchant_type).include? "I am an individual"
  end

  def name
    name = (self.first_name + " "+ self.last_name)
    name
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource only: [:show, :edit, :delete_account, :destroy, :send_reset_password]
  # GET /index
  # This action have 2 params: :search_email and :user_type
  # :search_email is string for search like with column Email.
  # :user_type is string for search with column user_type (ex: 'client' or 'merchant')
  def index
    if params[:search_email] && params[:user_type] # if search like by email and have filter by user_type
      if params[:user_type] =='all'
        @users = User.where(["LOWER(email) like ? and admin=false", "%#{params[:search_email].downcase}%" ]).order("created_at DESC").page(params[:page])
      else
        @users = User.where(["LOWER(email) like ? and user_type=? and admin=false", "%#{params[:search_email].downcase}%","#{params[:user_type]}" ]).order("created_at DESC").page(params[:page])
      end
    else # if filter only by user_type
      if params[:user_type]=='client' ||  params[:user_type]=='merchant'
        @users= User.where(user_type: params[:user_type], admin: false).order("created_at DESC").page(params[:page])
      else #default GET action
        @users= User.where(admin: false).order("created_at DESC").page(params[:page])
      end
    end
  end
  ##
  # GET
  def new
    @user= User.new
  end

  # POST
  def new_step2
    if params[:user][:user_type] == "merchant"
      session[:user_params] = user_params
      @user = User.new
      render 'add_account_merchant.js.erb'
    else
      password_length = 8
      password = Devise.friendly_token.first(password_length)
      @user = User.new(user_params.merge(password: password))
      @user.skip_confirmation!
      if @user.save
        data = {}
        data[:email] = params[:user][:email]
        data[:password] = password
        UserMailer.delay.send_email_client(data)
        flash[:notice]= t("users.new.new_successful")
      end
    end
  end
  # POST
  def create
    authorize! :manage, User
    password_length = 8
    password = Devise.friendly_token.first(password_length)
    @user = User.new(user_params_with_merchant.merge(password: password))
    @user.skip_confirmation!
    if @user.save
      data = {}
      data[:email] = user_params_with_merchant[:email]
      data[:password] = password
      data[:merchant_data] = user_params_with_merchant[:merchant_detail_attributes]
      UserMailer.delay.send_email_merchant(data)
      flash[:notice]= t("users.new.new_successful")
    end
  end
  # PUT /user_management/update_info_user
  def update
    if merchant_account_update_params[:virtual_money].blank?
      @merchant_detail = MerchantDetail.find_by_id (merchant_account_update_params[:merchant_detail_attributes][:id])
      if @merchant_detail.update(merchant_account_update_params[:merchant_detail_attributes])
        flash[:notice]= t("users.edit_one_profile.saved_successful")
      end
    else
      user = User.find_by_id([params[:id]])
      amount = merchant_account_update_params[:virtual_money].to_f - user.virtual_money
      if user.update(:virtual_money => merchant_account_update_params[:virtual_money].to_f)
        HistoryVMoney.create(amount: amount, user_id: user.id, action: 2,   )
        flash[:notice]= t("users.edit_one_profile.saved_successful")
      else
        flash[:alert]= t("users.edit_one_profile.unsave_msg")
      end
    end
  end
  ##
  # GET /show_one_profile/:id
  def show
  end
  ##
  # GET /edit_one_profile/:id
  def edit
  end
  ##
  # GET
  def delete_account
  end
  ##
  # DELETE
  # Note: Can't not delete user when user still have promotion active.
  # And must be alert can't be delete, reason abc ...
  def destroy
    if @user.destroy
      flash[:notice]= t("users.delete_one_profile.deleted_successful")
    end
  end
  ##
  # POST
  def send_reset_password
    @user.send_reset_password_instructions
  end

  def business_address
    billing_detail = current_user.billing_detail.nil? ? nil : current_user.billing_detail.as_json(only: ["first_name", "last_name", "street_address", "city", "zipcode", "state", "street_address_2", "email", "phone"])

    merchant_detail = current_user.merchant_detail.nil? ? nil : current_user.merchant_detail.as_json(only:  ["street_address", "city", "state", "zipcode"])
    json_response = {
      billing_detail: billing_detail,
      merchant_detail: merchant_detail,
      user_detail: current_user.as_json(only: ["phone_number", 'first_name', 'last_name'])
    }
    render json: json_response
  end

  def crop_avatar
    @avatar = image_service.update_crop_avatar(image_params, params[:avatar_id])
    if @avatar.errors.empty?
      @avatar.reprocess_avatar!
      @avatar_url = @avatar.avatar.url(:medium)
    else
      render 'crop_avatar_fail.js.erb'
    end
  end
  ##
  private
  # Params
  def merchant_account_update_params
    params.require(:user).permit(:email, :phone_number, :virtual_money, :merchant_detail_attributes => [:id,:business_name, :street_address, :city, :state, :zipcode])
  end

  def user_params
    params.require(:user).permit(:email, :email_confirmation,:user_type, :agree_with_tos, :phone_number)
  end

  def user_params_with_merchant
    merchant_account_update_params.merge!(session[:user_params])
  end

  def image_params
    params.required(:image).permit(:image, :avatar, :image_no, :description_image, :image_default, :crop_x, :crop_y, :crop_w, :crop_h, :user_id, :img_id, :using_image)
  end

  def image_service
    @images ||= ImageService.new()
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_error_messages!
    return '' if @user.errors.empty?

    messages = @user.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: @user.errors.count,
      resource: @user.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <ul> #{messages} </ul>
    </div>
    HTML
    return html
  end
  def user_error_messages?
    @user.errors.empty? ? false : true
  end

  # Get id of image if user have avatar
  def get_image_avatar_id user
    user.images.find_by_using_image("avatar")
  end
end

app/views/users/_add_account_merchant.html.haml
.modal.fade{ :id => "new_merchant_profile_modal" ,"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
        %h4#myModalLabel.modal-title.text-center= t("common.add_acc")
      .modal-body
        .row
          .col-md-10.col-md-offset-1
            - @user.build_merchant_detail if @user.merchant_detail.nil?
            = form_for(@user, url: users_path(@user), html: { method: :post, :remote => true }) do |f|
              .row
                .col-md-8.col-md-offset-2
                  = f.fields_for :merchant_detail do |mf|
                    .form-group
                      = mf.label t("devise.registrations.edit.business_name_label")
                      = mf.text_field :business_name, class: "form-control", autofocus: true
                    .form-group
                      = mf.label t("devise.registrations.edit.street_address_label")
                      = mf.text_field :street_address, class: "form-control"
                    .form-group
                      .row
                        .col-md-6.col-sm-6
                          = mf.label t("devise.registrations.edit.city_label")
                          = mf.text_field :city, class: "form-control"
                        .col-md-6.col-sm-6
                          = mf.label t("devise.registrations.edit.state_label")
                          = mf.text_field :state, class: "form-control"
                    .form-group
                      .row
                        .col-md-6
                          = mf.label t("devise.registrations.edit.zipcode_label")
                          = mf.text_field :zipcode, class: "form-control"
                        .col-md-6
                          = mf.label t("devise.registrations.edit.phone_number_label")
                          = mf.text_field :phone_number, class: "form-control"
                  = f.fields_for :merchant_detail do |mf|
                    = mf.file_field :logo
                  %p.text-center
                    = f.submit t("common.save"), class: "btn btn-default"
      .modal-footer
        %button.btn.btn-default{:type => "button", "data-dismiss" => "modal" }= t("common.close")

app/views/users/_edit_one_profile.html.haml
.modal.fade{ :id => "edit_profile_user" ,"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", }
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
        %h4#myModalLabel.modal-title.text-center= t("common.edit_profile")
      .modal-body
        = form_for(@user, url: user_path, html: { method: :put, id: "new_user",:remote => true }) do |f|
          = hidden_field_tag :authenticity_token, form_authenticity_token
          .row
            .col-md-8.col-md-offset-2
              .form-group
                = f.label t("devise.registrations.edit.email")
                = f.text_field :email, class: "form-control", required: true, autofocus: true, disabled: "disabled"
          - if @user.merchant_detail
            .row
              .col-md-8.col-md-offset-2
                = f.fields_for :merchant_detail do |mf|
                  .form-group
                    = mf.label t("devise.registrations.edit.business_name_label")
                    = mf.text_field :business_name, class: "form-control", required: true, autofocus: true
                  .form-group
                    = mf.label t("devise.registrations.edit.street_address_label")
                    = mf.text_field :street_address, class: "form-control", required: true
                  .form-group
                    .row
                      .col-md-6.col-sm-6
                        = mf.label t("devise.registrations.edit.city_label")
                        = mf.text_field :city, class: "form-control", required: true
                      .col-md-6.col-sm-6
                        = mf.label t("devise.registrations.edit.state_label")
                        = mf.text_field :state, class: "form-control", required: true
                  .form-group
                    .row
                      .col-md-6
                        = mf.label t("devise.registrations.edit.zipcode_label")
                        = mf.text_field :zipcode, class: "form-control", required: true
                      .col-md-6
                        = mf.label t("devise.registrations.edit.phone_number_label")
                        = mf.text_field :phone_number, class: "form-control", required: true
                  .form-group
                    .row
                      .col-md-6
                        =link_to t("common.forgot_pass"),send_reset_password_user_path(@user),remote: true, method: :post, class: "btn btn-primary"
                  = f.fields_for :merchant_detail do |mf|
                    .col-md-4= image_tag(@user.merchant_detail.logo.url(:thumb), size: "100x100")
                    .col-md-8= mf.file_field :logo
                  .clearfix
          - else
            .row
              .col-md-8.col-md-offset-2
                .form-group
                  = f.label t("devise.registrations.edit.virtual_money")
                  = f.text_field :virtual_money  , class: "form-control", required: true, autofocus: true
            .row
              .col-md-8.col-md-offset-2
                .form-group
                  .row
                    .col-md-6
                      =link_to t("common.forgot_pass"),send_reset_password_user_path(@user),remote: true, method: :post, class: "btn btn-primary"
      .modal-footer
        %button.btn.btn-success{ :id=> "update_profile_btn", :type => "button"}= t("common.update")
        %button.btn.btn-default{"data-dismiss" => "modal","data-target" => "#edit_profile_user", :type => "button"}= t("common.close")

app/views/users/_new.html.haml
.modal.fade{ :id => "add_account" ,"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", "data-target" => "add_account", :type => "button"} &times;
        %h4#myModalLabel.modal-title.text-center= t("common.add_acc")
      .modal-body
        #notice_here
        .row
          .col-xs-1.col-md-1
          .col-xs-10.col-md-10
            .row.form-horizontal
              = form_for(@user, :url => new_step2_users_path(@user), :html => { :method => :post }, :remote => true) do |f|
                .row.form-group.col-sm-10.col-md-12
                  .col-md-5.col-xs-4.control-label= f.label :email, t(".email")
                  .col-md-6.col-xs-8= f.email_field :email, :autofocus => true,id: "user_email_sign_up", class: "form-control"
                .row.form-group.col-sm-10.col-md-12
                  .col-md-5.col-xs-4.control-label= f.label :email_confirmation, t(".confirm_email")
                  .col-md-6.col-xs-8= f.email_field :email_confirmation, class: "form-control"
                .clearfix
                .row.text-center
                  .btn-group
                    = f.radio_button :user_type, 'client'
                    = f.label :user_type_client, t(".client")
                    = f.radio_button :user_type, 'merchant', :checked => true
                    = f.label :user_type_merchant, t(".merchant")
                .row.text-center.btn-group-horizontal
                  = button_tag t("common.cancel"), :type => 'reset', class: "btn btn-default"
                  = f.submit t(".continue"), class: "btn btn-default"
          .col-xs-1.col-md-1
      .modal-footer
        %button.btn.btn-default{:type => "button", "data-dismiss" => "modal", "data-target" => "add_account" }= t("common.close")

app/views/users/_notice_errors.html.haml
= form_notice_alert!

app/views/users/_show_one_profile.html.haml
- if @user.merchant_detail
  .modal.fade{ :id => "show_profile_user" ,"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
          %h4#myModalLabel.modal-title.text-center= t("common.profile")
        .modal-body
          .row
            .col-md-8.col-md-offset-2
              .col-md-4.pull-left
                = image_tag(@user.merchant_detail.logo.url(:thumb),size: "100x100")
              .col-md-8
                .row.form-group
                  = label_tag t("devise.registrations.edit.business_name_label")
                  = @user.merchant_detail.business_name
                .row.form-group
                  = label_tag t("devise.registrations.edit.street_address_label")
                  = @user.merchant_detail.street_address
              .form-group
                .row
                  .col-md-6.col-sm-6
                    = label_tag t("devise.registrations.edit.city_label")
                    = @user.merchant_detail.city
                  .col-md-6.col-sm-6
                    = label_tag t("devise.registrations.edit.state_label")
                    = @user.merchant_detail.state
              .form-group
                .row
                  .col-md-6
                    = label_tag t("devise.registrations.edit.zipcode_label")
                    = @user.merchant_detail.zipcode
                  .col-md-6
                    = label_tag t("devise.registrations.edit.phone_number_label")
                    = @user.merchant_detail.phone_number
        .modal-footer
          %button.btn.btn-default{:type => "button", "data-dismiss" => "modal" }= t("common.close")

app/views/users/_user.html.haml
=link_to new_user_path, remote: true , class: "btn btn-info m-b-medium" do
  %i.fa.fa-plus
  = t("common.add")
.table-responsive
  %table.table.table-bordered.table-hover
    %thead
      %tr
        %th.text-center No.
        %th= t(".email")
        %th= t(".user_type")
        %th= t(".created_at")
        %th= t(".action")
    %tbody
      - if @users.count > 0
        - @users.each_with_index do |user, index|
          - @page = params[:page].blank? ? 1 : params[:page].to_i
          %tr{ :id => user.id}
            %td.text-center= (@page-1)*PER_PAGE+index+1
            %td
              =link_to  user.email, edit_user_path(user), remote: true
            %td= user.user_type
            %td= user.created_at.to_time.strftime('%B %e %Y at %l:%M %p')
            %td{:colspan => "1"}
              -if user.user_type=='merchant'
                .col-md-12.user_pading= link_to t("common.delete"), delete_account_user_path(user), remote: true, class: "btn btn-full btn-danger"
              -else
                .col-md-12.user_pading= link_to t("common.delete"), delete_account_user_path(user), remote: true, class: "btn btn-full btn-danger"
      -else
        %tr
          %td{:colspan => "4"}= t(".no_record")
  #modal_here

app/views/users/add_account_merchant.js.erb
$('#add_account').modal('hide');
$('#add_account').remove();
$(".modal-backdrop").remove();
$('#modal_here').html('<%= j render "users/add_account_merchant" %>');
$('#new_merchant_profile_modal').modal('show');
add_validation_user();

app/views/users/add_email.html.haml
#add-email.container
  = form_for(@user, :as => 'user', :url => add_user_email_path(@user), :html => { role: 'form'}) do |f|
    - if @show_errors && @user.errors.any?
      #error_explanation
      - form_errors!(@user)
    .form-horizontal
      = f.label :email, t(".email")
      .controls
        = f.email_field :email, :autofocus => true, class: "form-control input-lg"
    .actions
      %p.text-center= f.submit t(".continue"), class: "btn btn-primary"

app/views/users/create.js.erb
$("#error_crud_here").html('<%=j render "users/notice_errors" %>');
<%= flash[:notice] = nil %>
$('#new_merchant_profile_modal').modal('hide');
$('#new_merchant_profile_modal').remove();
$(".modal-backdrop").remove();
add_validation_user();

app/views/users/crop_avatar.js.erb
// <!-- Get infor avatar -->
$("#user_avatar_url").val("<%= @avatar_url %>");
$(".avatar-for-user").attr('src', '<%= @avatar_url %>');
$("#pic_profile").val("<%= @avatar.id %>");
// <!-- Hide and remove modal -->
$("#crop-image-avatar").modal('hide');
$("#crop-image-avatar, .modal-backdrop").remove();
$.unblockUI();
// Call again crop image
window.Pages['CommonJs'].uploadImageAfterChange("#image_avatar", "#upload-avatar");

app/views/users/index.html.haml
.row
  .col-xs-10.col-md-10.col-xs-offset-1.col-md-offset-1
    .row.text-center
      %p.logo
        = image_tag("big_fun_icon.png", alt: t("devise.registrations.edit.logo"))
    .row
      .col-md-8.col-sm-8.col-xs-10.col-md-offset-4.col-sm-offset-3.col-xs-offset-1.text-center#inline_control
        = form_tag({:action => 'index'}, {:method => 'get', :role => "form", :id => 'search_form', :class => "form form-inline pull-left", :remote=> true}) do
          .row.form-horizontal
            .form-group.col-md-6.col-sm-6.col-xs-6.custom-placeholder
              %label{:for => "search_email"}=t(".email")
              %input.form-control{ type: :input, name: "search_email", id: "search_email"}
            .col-md-3.col-sm-3.col-xs-3
              %input.btn.btn-default{ :id => "search_submit", type: "submit",  :name => nil, value: t(".search"), :remote => true}
            .col-md-3.col-sm-3.col-xs-3
              = select_tag :user_type, options_for_select([[I18n.t("users.index.all"), "all"], [I18n.t("users.index.client"), "client"], [I18n.t("users.index.merchant"), "merchant"]]), :class => "form-control"
    .row#table_user
      = render  "users/user"
    .row.text-center#paganite_user
      = paginate @users, :remote => true

app/views/users/index.js.erb
$('#table_user').html('<%= j render "users/user" %>');
$('#paganite_user').html('<%= j (paginate(@users, :remote => true).to_s) %>');

app/views/users/new.js.erb
$('#modal_here').html('<%= j render "users/new" %>');
$('#add_account').modal('show');
add_validation_user();

app/views/users/send_reset_password.js.erb
alert(I18n.t("users.edit_one_profile.send_reset_pass_successful"));