config/routes.rb
BookingApp::Application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get "/users/:id/add_email", to: "users#add_email", via: [:get, :patch, :post], as: :add_user_email
  get "/contact", to: "contact#index"
  post "/contact", to: "contact#send_contact"
  get "/contact_us_result", to: "contact#contact_us_result"
  get "/merchant_page", to: "home#merchant_page", as: :merchant_page

  post "promotions/:blackout_id/cancel_blackout", to: "promotions#cancel_blackout", as: :cancel_blackout
  get "/merchants/:merchant_id/business", to: "employees#business", as: :employees_business

  devise_for :users, path: :auth,
    controllers: {
      omniauth_callbacks: :omniauth_callbacks,
      registrations: :registrations,
      confirmations: :confirmations
    }

  devise_scope :user do
    get "/auth/change_password", to: "registrations#edit_password"
    post "/auth/new_profile", to: "registrations#new_profile"
    get "/auth/check_user_unique", to: "registrations#check_user_unique"
    get "/auth/confirmation_success", to: "registrations#comfirmation_success"
    get "/auth/billing_card", to: "registrations#billing_card"
    post "/auth/billing_card", to: "registrations#create_billing_card"
    get "/auth/index_regis", to: "registrations#index_regis"
    get "/auth/check_email_regis", to: "registrations#check_email_regis"
    get "/auth/account_regis", to: "registrations#account_regis"
    post "/auth/get_info_account", to: "registrations#get_info_account"
    get "/auth/:id/card", to: "registrations#card", as: :auth_card
    put "/auth/:id/card", to: "registrations#update_card"
    get "/auth/check_email_present", to: "sessions#check_email_present"
    get "/auth/index", to: "sessions#index"
    get "/auth/destroy", to: "sessions#destroy"
    post "/auth/create", to: "passwords#create", as: :reset_password
    post "/auth/create_billing_card_merchant", to: "registrations#create_billing_card_merchant"
    get "/auth/redirect", to: "sessions#redirect"

  end

  root 'home#index'

  resources :home, except: [:index] do
    collection do
      get 'check_password_page'
      get 'check_pass'
      get :privacy_policy
    end
  end
  # get '*path' => 'home#index'

  resources :users do
    collection do
      post "new_step2"
      post "crop_avatar"
    end
    member do
      get "delete_account"
      post "send_reset_password"
      get "business_address"
    end
  end
  resources :faqs do
    collection do
      get "search"
    end
  end

  resources :bookings do
    collection do
      post "create_new_booking"
      post "payment_booking_merchant"
      post "payment_booking_client"
    end
  end
  resources :images do
    collection do
      post "upload_image"
      post "upload_image_step3"
      post "upload_image_from_angular"
    end
  end

  resources :promotions do
    member do
      get "share"
      get "check_deletion"
      get "customer_contacts"
      post "set_cancel_reactive_status"
      get "reset_pricing"
      patch "update_pricing"
      post "apply_blackout"
      put :publish_promotion
    end
    collection do
      get "get_cus_email"
      get "add_image"
      post "upload_image"
      get "show_inactive"
      post "get_current_rank"
      get "get_blackout_details"
    end
  end

  resources :temp_promotions

  resources :calendars,only:[:index] do
    collection do
      get "get_promotion_for_blackout"
      get "get_events"
      get "get_segmented_events"
      get "export_to_google_calendar"
    end
  end
  resources :categories, except: [:show, :new] do
    member do
      get "delete"
    end
    collection do
      get "check_categories_unique"
    end
  end

  resources :activities do
    member do
      get "view_day"
      get "cus_month_calendars"
      get "data_day"
      get "booked"
      resources :reviews
      post "bookmark"
      get "remove_bookmark"
      get "remove_past_life"
    end
    collection do
      post "book"
      get "genre"
      get "my_activity"
      get "load_image"
    end
  end
  resources :my_activities,only: [:destroy, :index] do
    member do
      get "contact", to: "my_activities#contact"
      post "contact", to: "my_activities#send_contact"
      get "destroy"
    end
    collection do
      post "cancel_booking"
    end
  end
  resources :history_v_moneys,only: [:index] do
  end
  # always the last routes
  match '*unmatched_route', :to => 'application#raise_not_found!', :via => :all
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :check_password_page, :check_pass]
  skip_before_filter :check_password, :only => [:check_password_page, :check_pass]
  skip_before_filter :authenticate_user!, :only => [:privacy_policy]
  layout "promotions_layout", only: [:merchant_page]

  def index
  	redirect_to merchant_page_path and return  if current_user && current_user.user_type == "merchant"
  end

  def check_pass
    if params[:check][:pass] == CHECK_PASSWORD
      session[:check_password] = "1"
      redirect_to root_path
    else
      render "check_password_page", layout: "home_layout"
    end
  end

end

app/views/home/check_password_page.html.haml
%div.modal.fade#check-pass-modal{role: 'dialog'}
  %div.modal-dialog
    %div.modal-active
      %div.modal-content
        %div.modal-header
          %h3= t(".authenticate_requied")
        %div.modal-body
          %p
            %span=t(".popup-description")
          = form_for "check-pass", :url => check_pass_home_index_path, method: "get" do
            .form-group
              %label.control-label=t(".password")
              =password_field(:check, :pass, size: 20)
            .form-group.group-check-button
              %button.ok-btn{type: "submit"}=t(".login")
              %button.cancel-btn{"data-dismiss" => "modal"}=t(".cancel")
.check-pass-dialog
  %a{"data-toggle"=>"modal", "href"=>"#check-pass-modal"}
    = image_tag("check_password_page.png", class: "img-responsive")

app/views/home/index.html.haml
.main-view-container{"ui-view" => ""}
  / %h1.text-center This is home page

app/views/home/merchant_page.html.haml
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
%div.minheight
  %section.body-holder
    %div.container
      %div.row
        %div.col-xs-12
          %div.body-content
            %div.step-header
              %div.step-hdr
                = image_tag "landinglogo.svg", alt: "logo", width: "100%", height: "100px"
                %h1
                  = t(".header_page")
              %div.landbtn.row
                %a.col-xs-6{href: "javascript:void(0)"}
                  %button.btn.btn-u-in U-IN
                = link_to edit_user_registration_path, class: "col-xs-6" do
                  %button.btn.btn-profile Profile
                = link_to promotions_path, class: "col-xs-6" do
                  %button.btn.btn-promotion Promotion
                = link_to calendars_path, class: "col-xs-6" do
                  %button.btn.btn-calender Calendar
              %div.content-top
                %div.content-data
                  %h1 Welcome to U-IN?
                  %p
                    The most advanced simplicity for you and your clients to create and enjoy many adventures and experiences with the most favourite people in your life. Our app takes care of business for you and your clients so you can enjoy a great future of fun together. No more searching and wasting time. This is one thumb booking at its finest. Try it out and you will become accicted to the ease of finding and doing fun activities with your friends and family.

      %div.row
        %div.col-xs-12
          %div.body-content
            %div.img-div
              %div.center-img
                %a{href: "javascript:void(0)"}
                  = image_tag "uin-center-logo.svg", alt: 'uin-logo', width: '100%', height: '200px'
              %div.promo-img
                %a{href: "#"}
                = link_to promotions_path do
                  = image_tag "lpromote.svg", alt: 'uin-logo', width: '100%', height: '250px'
              %div.profile-img
                = link_to edit_user_registration_path do
                  = image_tag "lprofile.svg", alt: 'uin-logo', width: '100%', height: '150px'
              %div.cal-img
                = link_to calendars_path do
                  = image_tag "lcalendar.svg", alt: 'uin-logo', width: '100%', height: '250px'

      %div.row
        %div.col-xs-12
          %div.body-content
            %div.content-bottom
              %div.content-data
                %h3{style: 'color:#040404'}
                  In less than five minutes You will create, activate and promote your services.
                %h3{style: 'color:#000000;font-weight:bold'} Are U-IN?
                = link_to new_promotion_path do
                  %button.btn Start Here!
:javascript
  $("header").hide();

app/views/home/privacy_policy.html.haml
%body
  %section.body-holder#privacy-page
    .container
      .row
        .col-xs-12
          .body-content
            .step-header
              %div
                %h3
                  = t('.title')
              %div
                %p= t('.content').html_safe

            %div.back-btn-privacy
              <a href="javascript:void(0)", onclick="window.history.back()">
              %button.btn.btn-default Back
            %br