config/routes.rb
BookingApp::Application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get "/users/:id/add_email", to: "users#add_email", via: [:get, :patch, :post], as: :add_user_email
  get "/contact", to: "contact#index"
  post "/contact", to: "contact#send_contact"
  get "/contact_us_result", to: "contact#contact_us_result"
  get "/merchant_page", to: "home#merchant_page", as: :merchant_page

  post "promotions/:blackout_id/cancel_blackout", to: "promotions#cancel_blackout", as: :cancel_blackout
  get "/merchants/:merchant_id/business", to: "employees#business", as: :employees_business

  devise_for :users, path: :auth,
    controllers: {
      omniauth_callbacks: :omniauth_callbacks,
      registrations: :registrations,
      confirmations: :confirmations
    }

  devise_scope :user do
    get "/auth/change_password", to: "registrations#edit_password"
    post "/auth/new_profile", to: "registrations#new_profile"
    get "/auth/check_user_unique", to: "registrations#check_user_unique"
    get "/auth/confirmation_success", to: "registrations#comfirmation_success"
    get "/auth/billing_card", to: "registrations#billing_card"
    post "/auth/billing_card", to: "registrations#create_billing_card"
    get "/auth/index_regis", to: "registrations#index_regis"
    get "/auth/check_email_regis", to: "registrations#check_email_regis"
    get "/auth/account_regis", to: "registrations#account_regis"
    post "/auth/get_info_account", to: "registrations#get_info_account"
    get "/auth/:id/card", to: "registrations#card", as: :auth_card
    put "/auth/:id/card", to: "registrations#update_card"
    get "/auth/check_email_present", to: "sessions#check_email_present"
    get "/auth/index", to: "sessions#index"
    get "/auth/destroy", to: "sessions#destroy"
    post "/auth/create", to: "passwords#create", as: :reset_password
    post "/auth/create_billing_card_merchant", to: "registrations#create_billing_card_merchant"
    get "/auth/redirect", to: "sessions#redirect"

  end

  root 'home#index'

  resources :home, except: [:index] do
    collection do
      get 'check_password_page'
      get 'check_pass'
      get :privacy_policy
    end
  end
  # get '*path' => 'home#index'

  resources :users do
    collection do
      post "new_step2"
      post "crop_avatar"
    end
    member do
      get "delete_account"
      post "send_reset_password"
      get "business_address"
    end
  end
  resources :faqs do
    collection do
      get "search"
    end
  end

  resources :bookings do
    collection do
      post "create_new_booking"
      post "payment_booking_merchant"
      post "payment_booking_client"
    end
  end
  resources :images do
    collection do
      post "upload_image"
      post "upload_image_step3"
      post "upload_image_from_angular"
    end
  end

  resources :promotions do
    member do
      get "share"
      get "check_deletion"
      get "customer_contacts"
      post "set_cancel_reactive_status"
      get "reset_pricing"
      patch "update_pricing"
      post "apply_blackout"
      put :publish_promotion
    end
    collection do
      get "get_cus_email"
      get "add_image"
      post "upload_image"
      get "show_inactive"
      post "get_current_rank"
      get "get_blackout_details"
    end
  end

  resources :temp_promotions

  resources :calendars,only:[:index] do
    collection do
      get "get_promotion_for_blackout"
      get "get_events"
      get "get_segmented_events"
      get "export_to_google_calendar"
    end
  end
  resources :categories, except: [:show, :new] do
    member do
      get "delete"
    end
    collection do
      get "check_categories_unique"
    end
  end

  resources :activities do
    member do
      get "view_day"
      get "cus_month_calendars"
      get "data_day"
      get "booked"
      resources :reviews
      post "bookmark"
      get "remove_bookmark"
      get "remove_past_life"
    end
    collection do
      post "book"
      get "genre"
      get "my_activity"
      get "load_image"
    end
  end
  resources :my_activities,only: [:destroy, :index] do
    member do
      get "contact", to: "my_activities#contact"
      post "contact", to: "my_activities#send_contact"
      get "destroy"
    end
    collection do
      post "cancel_booking"
    end
  end
  resources :history_v_moneys,only: [:index] do
  end
  # always the last routes
  match '*unmatched_route', :to => 'application#raise_not_found!', :via => :all
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :promotions
  has_and_belongs_to_many :temp_promotions
  belongs_to :user

  validates :name, presence: true
  validates :name, uniqueness: true
  validates_length_of :name, maximum: 255
end

app/models/user.rb
class User < ActiveRecord::Base

  ratyrate_rater
   
  TEMP_EMAIL_REGEX = /change@me.com/
  USER_TYPE = {
    merchant: "merchant",
    client: "client",
    admin: "admin"
  }

  attr_accessor :agree_with_tos, :type_sign_up, :search_email

  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :async
  ##
  # Relationships
  has_one :merchant_detail, dependent: :destroy
  has_one :billing_detail, dependent: :destroy
  # belongs_to :billing_detail, dependent: :destroy
  has_many :identitys, dependent: :destroy
  has_many :promotions, dependent: :destroy
  has_many :temp_promotions, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :categories
  has_many :history_v_moneys
  has_many :images
  has_many :reviews
  has_many :bookmarks
  
  ##
  # Nested models
  accepts_nested_attributes_for :merchant_detail, :billing_detail

  ##
  # Validates
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, uniqueness: true, on: :create
  validates :agree_with_tos, acceptance: true
  validates :email, presence: true
  delegate :can?, :cannot?, to: :ability

  def ability
    @ability ||= Ability.new(self)
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)
    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth.provider, auth.uid)
    user = identity.user ? identity.user : signed_in_resource
    user
  end

  ##
  # Check if user is admin
  def admin?
    self.admin
  end

  ##
  # Check if user is merchant
  def merchant?
    !self.admin? && self.user_type == USER_TYPE[:merchant]
  end

  ##
  # Check if user is client
  def client?
    self.user_type == USER_TYPE[:client]
  end

  def business_account?
    !Merchant.find(id).account_types.map(&:merchant_type).include? "I am an individual"
  end

  def name
    name = (self.first_name + " "+ self.last_name)
    name
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :load_category, only: [:destroy, :delete, :edit]
  def index
    authorize! :admin, Category
    if !params[:name].blank?
      @categories = Category.where(["LOWER(name) like ?", "%#{params[:name].downcase}%" ]).order("name ASC").page(params[:page])
    else
      @categories = Category.order("name ASC").page(params[:page])
    end
  end
  ##
  #
  def create
    authorize! :write, Category
    if params[:suggest_category]
      data = {}
      data[:first_name] = params_category[:first_name]
      data[:last_name] = params_category[:last_name]
      data[:suggest_catr] = params_category[:suggest_catr]
      data[:date_time] = Time.zone.now.to_date
      data[:email] = params_category[:email]
      UserMailer.delay.send_suggest_new_category_to_admin(data)
    else
      category = current_user.categories.new(name: params[:category][:name])
      if category.save
        flash.now[:notice]= t("categories.categories.created_succesfull")
      end
    end
  end
  ##
  #
  def edit
    authorize! :admin, Category
  end
  def update
    authorize! :admin, Category
    @category = Category.find(params[:id])
    unless Category.where.not(id: params[:id]).find_by_name(params[:category][:name])
      if @category.update(update_category_params)
        flash[:notice]= t("categories.update.update_successfull")
      else
        flash[:error]= t("categories.update.update_fail")
      end
    else
      flash[:error]= t("categories.update.update_exist")
    end
  end
  ##
  #GET
  def delete
    authorize! :admin, Category
  end
  # DELETE
  def destroy
    authorize! :admin, Category
    if !@category.blank?
      if @category.destroy
        flash[:notice]= t("categories.delete.destroy_successfull")
      end
    end
  end
  ##
  # JS CHECK Category Name
  def check_categories_unique
    authorize! :read, Category
    @category = Category.find_by_name(params[:category][:name])
    render :json => !@category
  end
  ##
  # Private
  private
    def load_category
      @category = Category.find_by_id(params[:id])
    end
    def update_category_params
      params.require(:category).permit(:name)
    end
    def params_category
      params.require(:category).permit(:first_name,:last_name,:company_name,:email,:suggest_catr)
    end
end

app/views/categories/_categories.html.haml
.row
  .col-md-6.col-md-offset-3.col-xs-8.col-xs-offset-2.text-center
    .form-group.col-md-8.col-sm-8.col-xs-8.custom-placeholder
      %label{:for => "search_name"}=t(".name")
      %input.form-control{ type: :input, name: "search_email", id: "search_name"}
    .col-md-3.col-sm-3.col-xs-3
      %button.btn.btn-default{ :id => "btn_search_name", type: "button", :remote => true}= t(".search")
%row.form-group.text-left
  %button.btn.btn-info.m-b-medium{id: "btn_request_category", type: "button","data-target" => "#request_category", "data-toggle" => "modal"}
    %i.fa.fa-plus
    =t(".add_category")
.table-responsive
  %table.table.table-bordered.table-hover
    %thead
      %tr
        %th.col-md-1.col-sm-1.col-xs-1.text-center= t(".number_no")
        %th.col-md-3.col-sm-3.col-xs-3= t(".name")
        %th.col-md-3.col-sm-3.col-xs-3= t(".created_by")
        %th.col-md-3.col-sm-3.col-xs-3= t(".created_at")
        %th.col-md-2.col-sm-2.col-xs-2= t(".action")
    %tbody
      - if @categories.count > 0
        - @categories.each_with_index do |c, index|
          - @page = params[:page].blank? ? 1 : params[:page].to_i
          %tr
            %td.text-center= (@page-1)*PER_PAGE+index+1
            %td
              =link_to  c.name, edit_category_path(c), remote: true
            - if current_user && current_user.admin
              %td Admin
            - else
              %td= User.find_by_id(c.user_id).email
            %td= c.created_at.to_time.strftime('%B %e %Y at %l:%M %p')
            %td
              .col-md-12.user_pading= link_to t("common.delete"),  delete_category_path(c), remote: true, class: "btn btn-full btn-danger"
.row.text-center#paganite_categories
  = paginate @categories, :remote => true
#modal_del_category

app/views/categories/_categories_list.html.haml
- categories_list = Category.all.order("name ASC")
- categories_list.find_in_batches(batch_size: ((categories_list.size.to_f)/2).ceil) do |categories|
  %div.catr-col.col-xs-6
    -categories.each do |category|
      %p.catr-row
        %input.catr-chbox{type: "checkbox", value: "", name: "check"  }
        = check_box_tag "promotion[category_ids][]", category.id, @promotion.category_ids.include?(category.id)
        %label.catr-lbl
          %span
          = category.name

app/views/categories/_delete.html.haml
.modal.fade{:id => "del_category", "aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
        %h4#myModalLabel.modal-title= t(".confirm_title")
      .modal-body
        .text-center
          %p= t(".delete_msg", name: @category.name)
        #btn_control.text-center
          = link_to t(".delete_btn"), category_path(@category.id), method: :delete,  remote: true, class: "btn btn-danger"
          %button.btn.btn-default{"data-dismiss" => "modal", "data-target" => "#confirm-delete" ,:type => "button"}= t(".btn_close")

app/views/categories/_form.html.haml
.modal.fade{ :id => "form_category" ,"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
        %h4#myModalLabel.modal-title= t(".add_modal")
      .modal-body
        .row
          .col-xs-1.col-md-1.col-ms-1
          .col-xs-10.col-md-10.col-ms-10
            .row.form-horizontal
              = form_for(category, :remote => true ,:url => category_path(category), method: :put, html: {class: "frm_category"}) do |f|
                = hidden_field_tag :authenticity_token, form_authenticity_token
                = hidden_field_tag :from_management, "1"
                .row.form-group.col-sm-10.col-md-12
                  .col-md-4.col-xs-4.control-label
                    = f.label :name
                  .col-md-6.col-xs-8
                    = f.text_field :name, class: "form-control"
                .clearfix
                .row.text-center.btn-group-horizontal
                  = f.submit t(".add"), class: "btn btn-default"
          .col-xs-1.col-md-1.col-ms-1
      .modal-footer
        %button.btn.btn-default{:type => "button", "data-dismiss" => "modal", "data-target" => "request_category" }= t("common.close")

app/views/categories/create.js.erb
$("#ReqNewCatr").modal('hide');
$("#request_category").modal('hide');

app/views/categories/created_from_management.js.erb
$("#error_crud_here").html('<%=escape_javascript render("users/notice_errors") %>');
<%= flash[:notice] = nil %>
$("#request_category").modal('hide');
$.getScript("<%= categories_path %>");

app/views/categories/delete.js.erb
$('#modal_del_category').html('<%= j render "categories/delete" %>');
$("#del_category").modal('toggle');

app/views/categories/destroy.js.erb
$("#error_crud_here").html('<%=j render "users/notice_errors" %>');
<%= flash[:notice] = nil %>
$("#del_category").modal('hide');
$("body").removeClass("modal-open");
$(".modal-backdrop").remove();
$.getScript("<%= categories_path %>");

app/views/categories/edit.js.erb
$('#modal_edit').html('<%= j render("form", category: @category) %>');
$("#form_category").modal('toggle');
validation_category();

app/views/categories/index.html.haml
#categories_list_table.col-md-10.col-md-offset-1.col-sm-12
  = render "categories/categories"
#modal_new
  .modal.fade{ :id => "request_category" ,"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
          %h4#myModalLabel.modal-title= t(".add_modal")
        .modal-body
          .row
            .col-xs-1.col-md-1.col-ms-1
            .col-xs-10.col-md-10.col-ms-10
              .row.form-horizontal
                = form_for(Category.new, :remote => true ,:url => categories_path(Category.new), html: {class: "frm_category"}) do |f|
                  = hidden_field_tag :authenticity_token, form_authenticity_token
                  = hidden_field_tag :from_management, "1"
                  .row.form-group.col-sm-10.col-md-12
                    .col-md-4.col-xs-4.control-label
                      = f.label :name
                    .col-md-6.col-xs-8
                      = f.text_field :name, class: "form-control"
                  .clearfix
                  .row.text-center.btn-group-horizontal
                    = f.submit t(".add"), class: "btn btn-default"
            .col-xs-1.col-md-1.col-ms-1
        .modal-footer
          %button.btn.btn-default{:type => "button", "data-dismiss" => "modal", "data-target" => "request_category" }= t("common.close")
#modal_edit

app/views/categories/index.js.erb
$('#categories_list_table').html('<%= j render("categories/categories") %>');

app/views/categories/update.js.erb
$("#error_crud_here").html('<%=j render "users/notice_errors" %>');
<%= flash[:notice] = nil %>
$("#form_category").modal('hide');
$.getScript("<%= categories_path %>");